apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tradesphere

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - rbac.yaml
  - network-policy.yaml
  - infra.yaml
  - api-gateway.yaml
  - services.yaml
  - frontend.yaml
  - ingress.yaml
  - monitoring/prometheus.yaml
  - monitoring/grafana.yaml

commonLabels:
  app.kubernetes.io/part-of: tradesphere
  app.kubernetes.io/managed-by: kustomize
